# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    # Look for a `requirements.txt` or `requirements-dev.txt` in the
    # `root` and `docs` directories
    directories:
      - "/" # Location of requirements.txt or requirements-dev.txtq
      - "/docs" # Location of requirements.txt or requirements-dev.txt
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:00"
      timezone: "Europe/Amsterdam"
    commit-message:
      prefix: "fix"
      include: "scope" # Include the scope in the commit message

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:00"
      timezone: "Europe/Amsterdam"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:00"
      timezone: "Europe/Amsterdam"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:00"
      timezone: "Europe/Amsterdam"
