# Common healthcheck settings
x-healthcheck: &default-healthcheck
  interval: 5s
  timeout: 5s
  retries: 5

services:
  api:
    image: kjanat/pdf-extract-with-ocr:latest
    container_name: pdf-extract-api
    ports:
      - "${API_PORT:-8080}:80"
    environment:
      - IS_DOCKER_CONTAINER=true
    env_file:
      - .env
    volumes:
      - ${UPLOADS_DIR:-./uploads}:/app/uploads
    depends_on:
      - db
      - redis
      - worker
    restart: unless-stopped
    networks:
      - app-network

  worker:
    image: kjanat/pdf-extract-with-ocr:latest
    container_name: pdf-extract-celery-worker
    environment:
      - IS_DOCKER_CONTAINER=true
    env_file:
      - .env
    volumes:
      - ${UPLOADS_DIR:-./uploads}:/app/uploads
    depends_on:
      - db
      - redis
    command: python -m celery -A celery_worker.celery worker --loglevel=info
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: pdf-extract-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      <<: *default-healthcheck
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: pdf-extract-postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ocruser} -d ${POSTGRES_DB:-ocr}"]
      <<: *default-healthcheck
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
