name: OCR Service CI

on:
  push:
    branches: [ docker ]
  pull_request:
    branches: [ docker ]

jobs:
  build-multiarch:
    name: Build Docker images (multi-arch)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push using docker-bake.hcl configuration
    - name: Build and push Docker images
      uses: docker/bake-action@v6
      with:
        files: ./docker-bake.hcl
        push: true