name: Docker CI/CD

on:
  schedule:
    - cron: "31 11 * * *" # Daily at 11:31 UTC
  push:
    branches: ["master", "docker"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["master", "docker"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-platforms:
    name: Build images
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Login to DockerHub
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3

      # Extract metadata for Docker tags
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            kjanat/pdf-extract-with-ocr
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}
          annotations: |
            org.opencontainers.image.description:${REPO_DESCRIPTION}
            org.opencontainers.image.vendor=${{ github.event.repository.owner.login }}
            org.opencontainers.image.licenses="Proprietary"

      # Build and push common platforms
      - name: Build and push fast platforms
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          annotations: ${{ steps.meta.outputs.annotations }}

      # Sign the images (GitHub Container Registry only)
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          # Use a more explicit approach to ensure only ghcr.io images are signed
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: |
          echo "${{ steps.meta.outputs.tags }}" | grep "^ghcr.io/" | xargs -I {} cosign sign --yes {}@${DIGEST}