name: GitHub Pages (Mkdocs)
on:
  push:
    branches: ["master", "docker"]
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y node-semver
      - name: Update pip
        run: python3 -m pip install --upgrade pip
      - name: Install MkDocs and plugins
        run: python3 -m pip install --upgrade --requirement ./docs/mkdocs-requirements.txt
      - name: Build 
        run: mkdocs build --clean
      - name: Deploy to GitHub Pages
        run: |
          git add docs && git commit -m "Update site" || echo "No changes to commit"
          git push